import { jsPDF } from 'jspdf';
import * as XLSX from 'xlsx';
import './ExportPanel.css';

function ExportPanel({ results }) {
    const generatePDF = () => {
        const doc = new jsPDF();
        const { hpi, contamination, overallAssessment } = results.results;

        // Title
        doc.setFontSize(20);
        doc.setTextColor(59, 130, 246);
        doc.text('Heavy Metal Pollution Index Report', 20, 20);

        // Subtitle
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 28);

        // Sample Info
        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.text('Sample Information', 20, 45);
        doc.setFontSize(10);
        doc.text(`Sample ID: ${results.sampleId || 'N/A'}`, 20, 53);
        doc.text(`Location: ${results.location || 'N/A'}`, 20, 60);
        doc.text(`Coordinates: ${results.latitude || 'N/A'}, ${results.longitude || 'N/A'}`, 20, 67);
        doc.text(`Date: ${results.date || 'N/A'}`, 20, 74);

        // Overall Assessment
        doc.setFontSize(14);
        doc.text('Overall Assessment', 20, 90);
        doc.setFontSize(12);
        doc.setTextColor(
            overallAssessment.level === 'SAFE' || overallAssessment.level === 'ACCEPTABLE' ? 34 :
                overallAssessment.level === 'MARGINAL' ? 234 : 239,
            overallAssessment.level === 'SAFE' || overallAssessment.level === 'ACCEPTABLE' ? 197 :
                overallAssessment.level === 'MARGINAL' ? 179 : 68,
            overallAssessment.level === 'SAFE' || overallAssessment.level === 'ACCEPTABLE' ? 94 :
                overallAssessment.level === 'MARGINAL' ? 8 : 68
        );
        doc.text(`${overallAssessment.level}: ${overallAssessment.message}`, 20, 100);

        // HPI Results
        doc.setTextColor(0);
        doc.setFontSize(14);
        doc.text('Heavy Metal Pollution Index (HPI)', 20, 115);
        doc.setFontSize(11);
        doc.text(`Value: ${hpi.value}`, 20, 123);
        doc.text(`Classification: ${hpi.classification.label}`, 20, 130);
        doc.text(`Description: ${hpi.classification.description}`, 20, 137);

        // Contamination Index
        doc.setFontSize(14);
        doc.text('Degree of Contamination', 20, 152);
        doc.setFontSize(11);
        doc.text(`Cd (Total): ${contamination.Cd}`, 20, 160);
        doc.text(`mCd (Modified): ${contamination.mCd}`, 20, 167);
        doc.text(`Classification: ${contamination.mCdClassification.label}`, 20, 174);

        // Metal Breakdown Table Header
        doc.setFontSize(14);
        doc.text('Metal-by-Metal Analysis', 20, 195);

        // Table
        const tableTop = 203;
        const rowHeight = 7;
        doc.setFontSize(9);
        doc.setTextColor(100);
        doc.text('Metal', 20, tableTop);
        doc.text('Conc. (mg/L)', 50, tableTop);
        doc.text('Limit', 85, tableTop);
        doc.text('Sub-Index', 110, tableTop);
        doc.text('Cf', 140, tableTop);
        doc.text('Status', 160, tableTop);

        doc.setTextColor(0);
        hpi.breakdown.forEach((item, index) => {
            const y = tableTop + (index + 1) * rowHeight;
            if (y < 280) {
                doc.text(`${item.metal} (${item.name})`, 20, y);
                doc.text(item.concentration.toFixed(4), 50, y);
                doc.text(item.permissibleLimit.toString(), 85, y);
                doc.text(item.subIndex.toFixed(2), 110, y);
                const cf = contamination.breakdown.find(c => c.metal === item.metal);
                doc.text(cf ? cf.contaminationFactor.toString() : '-', 140, y);
                doc.setTextColor(item.exceedsLimit ? 239 : 34, item.exceedsLimit ? 68 : 197, item.exceedsLimit ? 68 : 94);
                doc.text(item.exceedsLimit ? 'Exceeds' : 'OK', 160, y);
                doc.setTextColor(0);
            }
        });

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text('Generated by HMPI Calculator | Based on WHO Drinking Water Guidelines', 20, 290);

        doc.save(`HMPI_Report_${results.sampleId || 'sample'}_${new Date().toISOString().split('T')[0]}.pdf`);
    };

    const exportToExcel = () => {
        const { hpi, contamination } = results.results;

        // Summary sheet data
        const summaryData = [
            ['Heavy Metal Pollution Index Report'],
            [''],
            ['Sample Information'],
            ['Sample ID', results.sampleId || 'N/A'],
            ['Location', results.location || 'N/A'],
            ['Latitude', results.latitude || 'N/A'],
            ['Longitude', results.longitude || 'N/A'],
            ['Date', results.date || 'N/A'],
            [''],
            ['Results'],
            ['HPI Value', hpi.value],
            ['HPI Classification', hpi.classification.label],
            ['Degree of Contamination (Cd)', contamination.Cd],
            ['Modified Cd (mCd)', contamination.mCd],
            ['mCd Classification', contamination.mCdClassification.label],
        ];

        // Detail sheet data
        const detailData = [
            ['Metal', 'Name', 'Concentration (mg/L)', 'Permissible Limit', 'Sub-Index (Qi)', 'Contamination Factor', 'Weight (Wi)', 'Exceeds Limit'],
            ...hpi.breakdown.map(item => {
                const cf = contamination.breakdown.find(c => c.metal === item.metal);
                return [
                    item.metal,
                    item.name,
                    item.concentration,
                    item.permissibleLimit,
                    item.subIndex,
                    cf ? cf.contaminationFactor : '',
                    item.weight,
                    item.exceedsLimit ? 'Yes' : 'No'
                ];
            })
        ];

        const wb = XLSX.utils.book_new();
        const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
        const wsDetail = XLSX.utils.aoa_to_sheet(detailData);

        XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');
        XLSX.utils.book_append_sheet(wb, wsDetail, 'Metal Analysis');

        XLSX.writeFile(wb, `HMPI_Data_${results.sampleId || 'sample'}_${new Date().toISOString().split('T')[0]}.xlsx`);
    };

    const exportToCSV = () => {
        const { hpi, contamination } = results.results;

        const headers = ['Metal', 'Name', 'Concentration_mgL', 'Permissible_Limit', 'Sub_Index', 'Contamination_Factor', 'Weight', 'Exceeds_Limit'];
        const rows = hpi.breakdown.map(item => {
            const cf = contamination.breakdown.find(c => c.metal === item.metal);
            return [
                item.metal,
                item.name,
                item.concentration,
                item.permissibleLimit,
                item.subIndex,
                cf ? cf.contaminationFactor : '',
                item.weight,
                item.exceedsLimit ? 'Yes' : 'No'
            ].join(',');
        });

        const csv = [headers.join(','), ...rows].join('\n');
        const blob = new Blob([csv], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `HMPI_Data_${results.sampleId || 'sample'}_${new Date().toISOString().split('T')[0]}.csv`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="export-panel card">
            <h2>📤 Export Results</h2>
            <p>Download your analysis results in various formats</p>

            <div className="export-buttons">
                <button className="btn btn-primary export-btn" onClick={generatePDF}>
                    <span className="export-icon">📄</span>
                    <span className="export-text">
                        <strong>PDF Report</strong>
                        <small>Formatted document with all results</small>
                    </span>
                </button>

                <button className="btn btn-success export-btn" onClick={exportToExcel}>
                    <span className="export-icon">📊</span>
                    <span className="export-text">
                        <strong>Excel Workbook</strong>
                        <small>Detailed data with multiple sheets</small>
                    </span>
                </button>

                <button className="btn btn-secondary export-btn" onClick={exportToCSV}>
                    <span className="export-icon">📋</span>
                    <span className="export-text">
                        <strong>CSV File</strong>
                        <small>Simple comma-separated values</small>
                    </span>
                </button>
            </div>
        </div>
    );
}

export default ExportPanel;
